// Meal ideas used for recommendations and the weekly planner.
// Ingredients are written the same way a user would type them, and calories are
// calculated by the same parser, so what you see is exactly what gets logged.

export const RECIPES = [
  // Breakfast
  { id: 'eggs-toast', name: 'Scrambled eggs on toast', meal: 'breakfast', tags: ['quick', 'high-protein', 'classic'],
    ingredients: '3 eggs, 2 slices whole wheat bread, 5g butter' },
  { id: 'overnight-oats', name: 'Overnight oats with blueberries', meal: 'breakfast', tags: ['sweet', 'make-ahead'],
    ingredients: '50g oats, 150ml milk, 100g blueberries, 1 tsp honey' },
  { id: 'yogurt-parfait', name: 'Greek yogurt parfait', meal: 'breakfast', tags: ['sweet', 'quick', 'high-protein'],
    ingredients: '170g greek yogurt, 40g granola, 100g strawberries, 1 tsp honey' },
  { id: 'avocado-toast', name: 'Avocado toast with a fried egg', meal: 'breakfast', tags: ['quick', 'classic'],
    ingredients: '2 slices whole wheat bread, half avocado, 1 egg' },
  { id: 'pb-banana-toast', name: 'Peanut butter & banana toast', meal: 'breakfast', tags: ['sweet', 'quick'],
    ingredients: '2 slices whole wheat bread, 1 tbsp peanut butter, 1 banana' },
  { id: 'protein-smoothie', name: 'Banana protein smoothie', meal: 'breakfast', tags: ['quick', 'high-protein', 'sweet', 'drink'],
    ingredients: '1 scoop protein powder, 1 banana, 250ml almond milk, 1 tbsp peanut butter' },
  { id: 'veggie-omelette', name: 'Veggie omelette with feta', meal: 'breakfast', tags: ['high-protein', 'low-carb'],
    ingredients: '3 eggs, 50g spinach, 50g mushrooms, 1 tomato, 20g feta, 1 tsp olive oil' },
  { id: 'tofu-scramble', name: 'Tofu scramble on toast', meal: 'breakfast', tags: ['high-protein'],
    ingredients: '200g tofu, 50g spinach, half bell pepper, 1 tsp olive oil, 1 slice whole wheat bread' },
  { id: 'pancakes-berries', name: 'Pancakes with raspberries', meal: 'breakfast', tags: ['sweet', 'weekend'],
    ingredients: '3 pancakes, 100g raspberries, 1 tbsp maple syrup' },
  { id: 'cottage-bowl', name: 'Cottage cheese, peach & walnuts', meal: 'breakfast', tags: ['high-protein', 'quick', 'sweet'],
    ingredients: '200g cottage cheese, 1 peach, 15g walnuts' },
  { id: 'porridge-apple', name: 'Apple cinnamon porridge', meal: 'breakfast', tags: ['sweet', 'warm'],
    ingredients: '50g oats, 250ml oat milk, 1 apple, 1 tsp maple syrup' },

  // Lunch
  { id: 'chicken-salad', name: 'Grilled chicken salad', meal: 'lunch', tags: ['high-protein', 'low-carb', 'salad'],
    ingredients: '150g chicken breast, 80g lettuce, 1 tomato, half cucumber, 1 tbsp olive oil' },
  { id: 'tuna-wrap', name: 'Tuna mayo wrap', meal: 'lunch', tags: ['quick', 'high-protein'],
    ingredients: '1 tortilla, 1 can tuna, 1 tbsp mayonnaise, 30g lettuce, 1 tomato' },
  { id: 'chickpea-quinoa', name: 'Mediterranean chickpea quinoa bowl', meal: 'lunch', tags: ['mediterranean', 'bowl'],
    ingredients: '150g quinoa, 100g chickpeas, half cucumber, 1 tomato, 40g feta, 1 tbsp olive oil' },
  { id: 'lentil-soup', name: 'Lentil & carrot soup with bread', meal: 'lunch', tags: ['warm', 'soup'],
    ingredients: '250g lentils, 1 carrot, half onion, 1 tsp olive oil, 1 slice whole wheat bread' },
  { id: 'turkey-sandwich', name: 'Turkey & cheddar sandwich', meal: 'lunch', tags: ['quick', 'classic', 'high-protein'],
    ingredients: '2 slices whole wheat bread, 80g turkey, 1 slice cheddar, 20g lettuce, 1 tomato' },
  { id: 'hummus-pita', name: 'Hummus veggie pita', meal: 'lunch', tags: ['quick', 'mediterranean'],
    ingredients: '1 pita, 60g hummus, 1 carrot, half cucumber, 30g feta' },
  { id: 'salmon-poke', name: 'Salmon poke bowl', meal: 'lunch', tags: ['asian', 'bowl', 'high-protein'],
    ingredients: '120g salmon, 150g rice, half avocado, half cucumber, 1 tbsp soy sauce' },
  { id: 'burrito-bowl', name: 'Black bean burrito bowl', meal: 'lunch', tags: ['mexican', 'spicy', 'bowl'],
    ingredients: '150g brown rice, 120g black beans, 50g corn, 50g salsa, half avocado' },
  { id: 'chicken-wrap', name: 'Chicken & hummus wrap', meal: 'lunch', tags: ['quick', 'high-protein'],
    ingredients: '1 tortilla, 120g chicken breast, 30g hummus, 30g spinach, half bell pepper' },
  { id: 'egg-salad', name: 'Egg & avocado salad', meal: 'lunch', tags: ['low-carb', 'salad'],
    ingredients: '3 eggs, half avocado, 80g lettuce, 100g cherry tomatoes, 1 tbsp salad dressing' },

  // Dinner
  { id: 'salmon-sweetpotato', name: 'Salmon, sweet potato & broccoli', meal: 'dinner', tags: ['high-protein', 'classic'],
    ingredients: '150g salmon, 1 sweet potato, 150g broccoli, 1 tsp olive oil' },
  { id: 'chicken-stirfry', name: 'Chicken veggie stir-fry with rice', meal: 'dinner', tags: ['asian', 'high-protein', 'quick'],
    ingredients: '150g chicken breast, 1 bell pepper, 100g broccoli, 1 carrot, 1 tbsp soy sauce, 1 tbsp olive oil, 150g rice' },
  { id: 'bolognese', name: 'Spaghetti bolognese', meal: 'dinner', tags: ['italian', 'pasta', 'classic'],
    ingredients: '200g spaghetti, 120g ground beef, 150g chopped tomatoes, half onion, 10g parmesan, 1 tsp olive oil' },
  { id: 'steak-potatoes', name: 'Steak with potatoes & green beans', meal: 'dinner', tags: ['high-protein', 'classic'],
    ingredients: '180g steak, 200g potatoes, 100g green beans, 5g butter' },
  { id: 'tofu-curry', name: 'Coconut tofu & cauliflower curry', meal: 'dinner', tags: ['indian', 'spicy', 'curry'],
    ingredients: '200g tofu, 150g cauliflower, 50g peas, half onion, 100ml coconut milk, 150g rice' },
  { id: 'shrimp-tacos', name: 'Shrimp tacos', meal: 'dinner', tags: ['mexican', 'spicy'],
    ingredients: '3 tortillas, 150g shrimp, 30g lettuce, 50g salsa, half avocado' },
  { id: 'chickpea-curry', name: 'Chickpea & spinach curry', meal: 'dinner', tags: ['indian', 'spicy', 'curry'],
    ingredients: '200g chickpeas, 100ml coconut milk, 100g spinach, 100g chopped tomatoes, half onion, 150g rice' },
  { id: 'chicken-quinoa', name: 'Chicken thigh, quinoa & zucchini', meal: 'dinner', tags: ['high-protein'],
    ingredients: '150g chicken thigh, 150g quinoa, 150g zucchini, 1 tsp olive oil' },
  { id: 'cod-couscous', name: 'Lemon cod with couscous', meal: 'dinner', tags: ['mediterranean', 'light'],
    ingredients: '150g cod, 150g couscous, 100g cherry tomatoes, half lemon, 1 tbsp olive oil' },
  { id: 'pizza-salad', name: 'Pizza night with side salad', meal: 'dinner', tags: ['italian', 'treat'],
    ingredients: '2 slices pizza, 60g lettuce, 1 tbsp salad dressing' },
  { id: 'pork-potato', name: 'Pork chop with mash & kale', meal: 'dinner', tags: ['classic', 'high-protein'],
    ingredients: '150g pork chop, 200g mashed potato, 5g butter, 60g kale' },
  { id: 'mushroom-pasta', name: 'Garlic mushroom pasta', meal: 'dinner', tags: ['italian', 'pasta'],
    ingredients: '200g pasta, 150g mushrooms, 20g parmesan, 2 cloves garlic, 1 tbsp olive oil' },
  { id: 'pesto-pasta-chicken', name: 'Chicken pesto pasta', meal: 'dinner', tags: ['italian', 'pasta', 'high-protein'],
    ingredients: '180g pasta, 120g chicken breast, 1 tbsp pesto, 100g cherry tomatoes' },
  { id: 'veggie-noodles', name: 'Tofu & veggie noodles', meal: 'dinner', tags: ['asian', 'quick'],
    ingredients: '200g noodles, 150g tofu, 1 bell pepper, 100g broccoli, 1 tbsp soy sauce, 1 tsp olive oil' },

  // Snacks
  { id: 'apple-pb', name: 'Apple with peanut butter', meal: 'snack', tags: ['sweet', 'quick'],
    ingredients: '1 apple, 1 tbsp peanut butter' },
  { id: 'yogurt-honey', name: 'Greek yogurt & honey', meal: 'snack', tags: ['high-protein', 'sweet'],
    ingredients: '170g greek yogurt, 1 tsp honey' },
  { id: 'hummus-carrots', name: 'Hummus & carrot sticks', meal: 'snack', tags: ['savory', 'quick'],
    ingredients: '60g hummus, 2 carrots' },
  { id: 'almonds', name: 'Handful of almonds', meal: 'snack', tags: ['quick', 'savory'],
    ingredients: '28g almonds' },
  { id: 'banana', name: 'Banana', meal: 'snack', tags: ['quick', 'sweet', 'fruit'],
    ingredients: '1 banana' },
  { id: 'cheese-crackers', name: 'Cheese & crackers', meal: 'snack', tags: ['savory'],
    ingredients: '30g cheddar, 5 crackers' },
  { id: 'protein-shake', name: 'Protein shake with milk', meal: 'snack', tags: ['high-protein', 'drink', 'post-workout'],
    ingredients: '1 scoop protein powder, 250ml milk' },
  { id: 'choc-strawberries', name: 'Dark chocolate & strawberries', meal: 'snack', tags: ['sweet', 'treat'],
    ingredients: '20g dark chocolate, 150g strawberries' },
  { id: 'cottage-pineapple', name: 'Cottage cheese & pineapple', meal: 'snack', tags: ['high-protein', 'sweet'],
    ingredients: '150g cottage cheese, 100g pineapple' },
  { id: 'ricecake-avocado', name: 'Rice cakes with avocado', meal: 'snack', tags: ['quick', 'savory'],
    ingredients: '2 rice cakes, half avocado' },
  { id: 'edamame', name: 'Salted edamame', meal: 'snack', tags: ['high-protein', 'savory', 'asian'],
    ingredients: '150g edamame' },
  { id: 'boiled-eggs', name: 'Two boiled eggs', meal: 'snack', tags: ['high-protein', 'low-carb', 'quick'],
    ingredients: '2 eggs' },
];
