// Meal ideas used for recommendations and the weekly planner.
// Ingredients are written the same way a user would type them, and calories are
// calculated by the same parser, so what you see is exactly what gets logged.

export const RECIPES = [
  // Breakfast
  { id: 'eggs-toast', name: 'Scrambled eggs on toast', meal: 'breakfast', tags: ['quick', 'high-protein', 'classic'],
    ingredients: '3 eggs, 2 slices whole wheat bread, 5g butter' },
  { id: 'overnight-oats', name: 'Overnight oats with blueberries', meal: 'breakfast', tags: ['sweet', 'make-ahead'],
    ingredients: '50g oats, 150ml milk, 100g blueberries, 1 tsp honey' },
  { id: 'yogurt-parfait', name: 'Greek yogurt parfait', meal: 'breakfast', tags: ['sweet', 'quick', 'high-protein'],
    ingredients: '170g greek yogurt, 40g granola, 100g strawberries, 1 tsp honey' },
  { id: 'avocado-toast', name: 'Avocado toast with a fried egg', meal: 'breakfast', tags: ['quick', 'classic'],
    ingredients: '2 slices whole wheat bread, half avocado, 1 egg' },
  { id: 'pb-banana-toast', name: 'Peanut butter & banana toast', meal: 'breakfast', tags: ['sweet', 'quick'],
    ingredients: '2 slices whole wheat bread, 1 tbsp peanut butter, 1 banana' },
  { id: 'protein-smoothie', name: 'Banana protein smoothie', meal: 'breakfast', tags: ['quick', 'high-protein', 'sweet', 'drink'],
    ingredients: '1 scoop protein powder, 1 banana, 250ml almond milk, 1 tbsp peanut butter' },
  { id: 'veggie-omelette', name: 'Veggie omelette with feta', meal: 'breakfast', tags: ['high-protein', 'low-carb'],
    ingredients: '3 eggs, 50g spinach, 50g mushrooms, 1 tomato, 20g feta, 1 tsp olive oil' },
  { id: 'tofu-scramble', name: 'Tofu scramble on toast', meal: 'breakfast', tags: ['high-protein'],
    ingredients: '200g tofu, 50g spinach, half bell pepper, 1 tsp olive oil, 1 slice whole wheat bread' },
  { id: 'pancakes-berries', name: 'Pancakes with raspberries', meal: 'breakfast', tags: ['sweet', 'weekend'],
    ingredients: '3 pancakes, 100g raspberries, 1 tbsp maple syrup' },
  { id: 'cottage-bowl', name: 'Cottage cheese, peach & walnuts', meal: 'breakfast', tags: ['high-protein', 'quick', 'sweet'],
    ingredients: '200g cottage cheese, 1 peach, 15g walnuts' },
  { id: 'porridge-apple', name: 'Apple cinnamon porridge', meal: 'breakfast', tags: ['sweet', 'warm'],
    ingredients: '50g oats, 250ml oat milk, 1 apple, 1 tsp maple syrup' },

  // Lunch
  { id: 'chicken-salad', name: 'Grilled chicken salad', meal: 'lunch', tags: ['high-protein', 'low-carb', 'salad'],
    ingredients: '150g chicken breast, 80g lettuce, 1 tomato, half cucumber, 1 tbsp olive oil' },
  { id: 'tuna-wrap', name: 'Tuna mayo wrap', meal: 'lunch', tags: ['quick', 'high-protein'],
    ingredients: '1 tortilla, 1 can tuna, 1 tbsp mayonnaise, 30g lettuce, 1 tomato' },
  { id: 'chickpea-quinoa', name: 'Mediterranean chickpea quinoa bowl', meal: 'lunch', tags: ['mediterranean', 'bowl'],
    ingredients: '150g quinoa, 100g chickpeas, half cucumber, 1 tomato, 40g feta, 1 tbsp olive oil' },
  { id: 'lentil-soup', name: 'Lentil & carrot soup with bread', meal: 'lunch', tags: ['warm', 'soup'],
    ingredients: '250g lentils, 1 carrot, half onion, 1 tsp olive oil, 1 slice whole wheat bread' },
  { id: 'turkey-sandwich', name: 'Turkey & cheddar sandwich', meal: 'lunch', tags: ['quick', 'classic', 'high-protein'],
    ingredients: '2 slices whole wheat bread, 80g turkey, 1 slice cheddar, 20g lettuce, 1 tomato' },
  { id: 'hummus-pita', name: 'Hummus veggie pita', meal: 'lunch', tags: ['quick', 'mediterranean'],
    ingredients: '1 pita, 60g hummus, 1 carrot, half cucumber, 30g feta' },
  { id: 'salmon-poke', name: 'Salmon poke bowl', meal: 'lunch', tags: ['asian', 'bowl', 'high-protein'],
    ingredients: '120g salmon, 150g rice, half avocado, half cucumber, 1 tbsp soy sauce' },
  { id: 'burrito-bowl', name: 'Black bean burrito bowl', meal: 'lunch', tags: ['mexican', 'spicy', 'bowl'],
    ingredients: '150g brown rice, 120g black beans, 50g corn, 50g salsa, half avocado' },
  { id: 'chicken-wrap', name: 'Chicken & hummus wrap', meal: 'lunch', tags: ['quick', 'high-protein'],
    ingredients: '1 tortilla, 120g chicken breast, 30g hummus, 30g spinach, half bell pepper' },
  { id: 'egg-salad', name: 'Egg & avocado salad', meal: 'lunch', tags: ['low-carb', 'salad'],
    ingredients: '3 eggs, half avocado, 80g lettuce, 100g cherry tomatoes, 1 tbsp salad dressing' },

  // Dinner
  { id: 'salmon-sweetpotato', name: 'Salmon, sweet potato & broccoli', meal: 'dinner', tags: ['high-protein', 'classic'],
    ingredients: '150g salmon, 1 sweet potato, 150g broccoli, 1 tsp olive oil' },
  { id: 'chicken-stirfry', name: 'Chicken veggie stir-fry with rice', meal: 'dinner', tags: ['asian', 'high-protein', 'quick'],
    ingredients: '150g chicken breast, 1 bell pepper, 100g broccoli, 1 carrot, 1 tbsp soy sauce, 1 tbsp olive oil, 150g rice' },
  { id: 'bolognese', name: 'Spaghetti bolognese', meal: 'dinner', tags: ['italian', 'pasta', 'classic'],
    ingredients: '200g spaghetti, 120g ground beef, 150g chopped tomatoes, half onion, 10g parmesan, 1 tsp olive oil' },
  { id: 'steak-potatoes', name: 'Steak with potatoes & green beans', meal: 'dinner', tags: ['high-protein', 'classic'],
    ingredients: '180g steak, 200g potatoes, 100g green beans, 5g butter' },
  { id: 'tofu-curry', name: 'Coconut tofu & cauliflower curry', meal: 'dinner', tags: ['indian', 'spicy', 'curry'],
    ingredients: '200g tofu, 150g cauliflower, 50g peas, half onion, 100ml coconut milk, 150g rice' },
  { id: 'shrimp-tacos', name: 'Shrimp tacos', meal: 'dinner', tags: ['mexican', 'spicy'],
    ingredients: '3 tortillas, 150g shrimp, 30g lettuce, 50g salsa, half avocado' },
  { id: 'chickpea-curry', name: 'Chickpea & spinach curry', meal: 'dinner', tags: ['indian', 'spicy', 'curry'],
    ingredients: '200g chickpeas, 100ml coconut milk, 100g spinach, 100g chopped tomatoes, half onion, 150g rice' },
  { id: 'chicken-quinoa', name: 'Chicken thigh, quinoa & zucchini', meal: 'dinner', tags: ['high-protein'],
    ingredients: '150g chicken thigh, 150g quinoa, 150g zucchini, 1 tsp olive oil' },
  { id: 'cod-couscous', name: 'Lemon cod with couscous', meal: 'dinner', tags: ['mediterranean', 'light'],
    ingredients: '150g cod, 150g couscous, 100g cherry tomatoes, half lemon, 1 tbsp olive oil' },
  { id: 'pizza-salad', name: 'Pizza night with side salad', meal: 'dinner', tags: ['italian', 'treat'],
    ingredients: '2 slices pizza, 60g lettuce, 1 tbsp salad dressing' },
  { id: 'pork-potato', name: 'Pork chop with mash & kale', meal: 'dinner', tags: ['classic', 'high-protein'],
    ingredients: '150g pork chop, 200g mashed potato, 5g butter, 60g kale' },
  { id: 'mushroom-pasta', name: 'Garlic mushroom pasta', meal: 'dinner', tags: ['italian', 'pasta'],
    ingredients: '200g pasta, 150g mushrooms, 20g parmesan, 2 cloves garlic, 1 tbsp olive oil' },
  { id: 'pesto-pasta-chicken', name: 'Chicken pesto pasta', meal: 'dinner', tags: ['italian', 'pasta', 'high-protein'],
    ingredients: '180g pasta, 120g chicken breast, 1 tbsp pesto, 100g cherry tomatoes' },
  { id: 'veggie-noodles', name: 'Tofu & veggie noodles', meal: 'dinner', tags: ['asian', 'quick'],
    ingredients: '200g noodles, 150g tofu, 1 bell pepper, 100g broccoli, 1 tbsp soy sauce, 1 tsp olive oil' },

  // Snacks
  { id: 'apple-pb', name: 'Apple with peanut butter', meal: 'snack', tags: ['sweet', 'crunchy', 'quick', 'pre-workout'],
    ingredients: '1 apple, 1 tbsp peanut butter' },
  { id: 'yogurt-honey', name: 'Greek yogurt & honey', meal: 'snack', tags: ['high-protein', 'sweet', 'creamy', 'post-workout'],
    ingredients: '170g greek yogurt, 1 tsp honey' },
  { id: 'hummus-carrots', name: 'Hummus & carrot sticks', meal: 'snack', tags: ['salty', 'crunchy', 'volume', 'quick'],
    ingredients: '60g hummus, 2 carrots' },
  { id: 'almonds', name: 'Handful of almonds', meal: 'snack', tags: ['quick', 'salty', 'crunchy'],
    ingredients: '28g almonds' },
  { id: 'banana', name: 'Banana', meal: 'snack', tags: ['quick', 'sweet', 'fruit', 'pre-workout'],
    ingredients: '1 banana' },
  { id: 'cheese-crackers', name: 'Cheese & crackers', meal: 'snack', tags: ['salty', 'crunchy'],
    ingredients: '30g cheddar, 5 crackers' },
  { id: 'protein-shake', name: 'Protein shake with milk', meal: 'snack', tags: ['high-protein', 'drink', 'post-workout', 'filling', 'sweet'],
    ingredients: '1 scoop protein powder, 250ml milk' },
  { id: 'choc-strawberries', name: 'Dark chocolate & strawberries', meal: 'snack', tags: ['sweet', 'treat', 'volume'],
    ingredients: '20g dark chocolate, 150g strawberries' },
  { id: 'cottage-pineapple', name: 'Cottage cheese & pineapple', meal: 'snack', tags: ['high-protein', 'sweet', 'creamy', 'filling'],
    ingredients: '150g cottage cheese, 100g pineapple' },
  { id: 'ricecake-avocado', name: 'Rice cakes with avocado', meal: 'snack', tags: ['quick', 'salty', 'crunchy'],
    ingredients: '2 rice cakes, half avocado' },
  { id: 'edamame', name: 'Salted edamame', meal: 'snack', tags: ['high-protein', 'salty', 'filling', 'asian'],
    ingredients: '150g edamame' },
  { id: 'boiled-eggs', name: 'Two boiled eggs', meal: 'snack', tags: ['high-protein', 'low-carb', 'quick', 'filling', 'salty'],
    ingredients: '2 eggs' },
  // ---------- More breakfasts ----------
  { id: 'protein-pancakes', name: 'Banana oat protein pancakes', meal: 'breakfast', tags: ['sweet', 'high-protein', 'weekend'],
    ingredients: '40g oats, 2 eggs, 1 banana, half scoop protein powder, 1 tsp olive oil, 50g berries' },
  { id: 'french-toast', name: 'French toast with berries', meal: 'breakfast', tags: ['sweet', 'weekend', 'warm'],
    ingredients: '2 slices bread, 1 egg, 50ml milk, 5g butter, 100g berries, 1 tsp maple syrup' },
  { id: 'smoothie-bowl', name: 'Berry smoothie bowl', meal: 'breakfast', tags: ['sweet', 'creamy', 'volume'],
    ingredients: '150g berries, 1 banana, 150g skyr, 20g granola' },
  { id: 'breakfast-burrito', name: 'Breakfast burrito', meal: 'breakfast', tags: ['mexican', 'high-protein', 'filling'],
    ingredients: '1 tortilla, 2 eggs, 60g black beans, 30g salsa, 20g cheddar' },
  { id: 'bagel-salmon', name: 'Bagel with smoked salmon & cream cheese', meal: 'breakfast', tags: ['weekend', 'high-protein'],
    ingredients: '1 bagel, 30g cream cheese, 50g smoked salmon, half cucumber' },
  { id: 'muesli-milk', name: 'Muesli with milk & banana', meal: 'breakfast', tags: ['quick', 'classic', 'sweet'],
    ingredients: '50g muesli, 200ml milk, half banana' },
  { id: 'quark-bowl', name: 'Quark bowl with berries & oats', meal: 'breakfast', tags: ['high-protein', 'sweet', 'creamy', 'filling'],
    ingredients: '250g quark, 100g berries, 30g oats, 1 tsp honey' },
  { id: 'broetchen-ham', name: 'Brötchen with ham & cheese', meal: 'breakfast', tags: ['classic', 'german', 'quick'],
    ingredients: '2 bread rolls, 5g butter, 30g ham, 1 slice cheddar, 1 tomato' },
  { id: 'broetchen-jam', name: 'Brötchen with butter & jam', meal: 'breakfast', tags: ['classic', 'german', 'sweet'],
    ingredients: '2 bread rolls, 10g butter, 2 tbsp jam' },
  { id: 'chia-pudding', name: 'Chia pudding with raspberries', meal: 'breakfast', tags: ['make-ahead', 'sweet', 'creamy'],
    ingredients: '2 tbsp chia seeds, 200ml almond milk, 100g raspberries, 1 tsp maple syrup' },
  { id: 'egg-muffins', name: 'Egg muffins with spinach & feta', meal: 'breakfast', tags: ['make-ahead', 'high-protein', 'low-carb'],
    ingredients: '3 eggs, 50g spinach, half bell pepper, 20g feta' },
  { id: 'shakshuka', name: 'Shakshuka with bread', meal: 'breakfast', tags: ['weekend', 'warm', 'spicy'],
    ingredients: '2 eggs, 200g chopped tomatoes, half bell pepper, half onion, 1 tsp olive oil, 1 slice bread' },
  { id: 'pb-overnight-oats', name: 'Peanut butter overnight oats', meal: 'breakfast', tags: ['make-ahead', 'sweet', 'filling'],
    ingredients: '50g oats, 150ml milk, 1 tbsp peanut butter, half banana' },
  { id: 'cottage-toast', name: 'Cottage cheese & tomato toast', meal: 'breakfast', tags: ['quick', 'high-protein', 'salty'],
    ingredients: '2 slices whole wheat bread, 100g cottage cheese, 100g cherry tomatoes' },
  { id: 'omelette-wrap', name: 'Spinach & feta omelette wrap', meal: 'breakfast', tags: ['high-protein', 'quick'],
    ingredients: '1 tortilla, 2 eggs, 30g spinach, 20g feta, 1 tsp olive oil' },
  { id: 'nutella-toast', name: 'Chocolate spread toast with banana', meal: 'breakfast', tags: ['sweet', 'treat'],
    ingredients: '2 slices bread, 1 tbsp chocolate spread, half banana' },
  { id: 'kefir-oats', name: 'Kefir oats with apple', meal: 'breakfast', tags: ['make-ahead', 'sweet'],
    ingredients: '50g oats, 200ml kefir, 1 apple, 10g walnuts' },

  // ---------- More lunches ----------
  { id: 'falafel-wrap', name: 'Falafel wrap with tzatziki', meal: 'lunch', tags: ['mediterranean', 'quick'],
    ingredients: '1 tortilla, 4 falafel, 40g lettuce, 1 tomato, 40g tzatziki' },
  { id: 'halloumi-salad', name: 'Halloumi & quinoa salad', meal: 'lunch', tags: ['salad', 'mediterranean'],
    ingredients: '60g halloumi, 100g quinoa, 60g lettuce, 100g cherry tomatoes, half cucumber, 1 tsp olive oil' },
  { id: 'caesar-wrap', name: 'Chicken caesar wrap', meal: 'lunch', tags: ['high-protein', 'quick'],
    ingredients: '1 tortilla, 120g chicken breast, 40g lettuce, 10g parmesan, 1 tbsp caesar dressing' },
  { id: 'tuna-pasta-salad', name: 'Tuna pasta salad', meal: 'lunch', tags: ['make-ahead', 'high-protein', 'pasta'],
    ingredients: '150g pasta, 1 can tuna, 50g corn, 1 tbsp mayonnaise, half cucumber' },
  { id: 'meal-prep-chicken', name: 'Meal-prep chicken, rice & broccoli', meal: 'lunch', tags: ['make-ahead', 'high-protein', 'filling', 'post-workout'],
    ingredients: '150g chicken breast, 150g rice, 150g broccoli, 1 tsp olive oil, 1 tbsp soy sauce' },
  { id: 'lentil-salad', name: 'Lentil & feta salad', meal: 'lunch', tags: ['salad', 'filling', 'mediterranean'],
    ingredients: '200g lentils, 40g feta, 1 tomato, half cucumber, 1 tbsp olive oil, half lemon' },
  { id: 'egg-fried-rice', name: 'Egg fried rice with peas', meal: 'lunch', tags: ['asian', 'quick'],
    ingredients: '180g rice, 2 eggs, 80g peas, 1 carrot, 1 tbsp soy sauce, 1 tsp olive oil' },
  { id: 'veg-soup-bread', name: 'Vegetable soup with bread', meal: 'lunch', tags: ['warm', 'soup', 'volume'],
    ingredients: '1 bowl vegetable soup, 2 slices whole wheat bread, 10g parmesan' },
  { id: 'tabbouleh', name: 'Bulgur tabbouleh with chickpeas', meal: 'lunch', tags: ['mediterranean', 'make-ahead'],
    ingredients: '150g bulgur, 100g chickpeas, 1 tomato, half cucumber, 1 tbsp olive oil, half lemon' },
  { id: 'chicken-noodle-soup', name: 'Chicken noodle soup', meal: 'lunch', tags: ['warm', 'soup', 'high-protein'],
    ingredients: '1 bowl soup, 100g chicken breast, 100g noodles, 1 carrot' },
  { id: 'baked-potato', name: 'Baked potato with cottage cheese & beans', meal: 'lunch', tags: ['filling', 'warm', 'high-protein'],
    ingredients: '1 large potato, 150g cottage cheese, 80g black beans, 20g lettuce' },
  { id: 'pita-pizza', name: 'Pita pizza', meal: 'lunch', tags: ['italian', 'quick', 'treat'],
    ingredients: '1 pita, 50g tomato sauce, 40g mozzarella, 50g mushrooms, half bell pepper' },
  { id: 'greek-salad', name: 'Greek salad with pita', meal: 'lunch', tags: ['salad', 'mediterranean'],
    ingredients: '2 tomatoes, 1 cucumber, 60g feta, half red onion, 1 tbsp olive oil, 1 pita' },
  { id: 'sushi-box', name: 'Sushi box with edamame', meal: 'lunch', tags: ['asian', 'quick'],
    ingredients: '8 pieces sushi, 100g edamame, 1 tbsp soy sauce' },
  { id: 'turkey-club', name: 'Turkey club sandwich', meal: 'lunch', tags: ['classic', 'high-protein'],
    ingredients: '3 slices whole wheat bread, 80g turkey, 2 slices bacon, 1 tomato, 20g lettuce, 1 tbsp mayonnaise' },
  { id: 'chicken-quesadilla', name: 'Chicken quesadilla', meal: 'lunch', tags: ['mexican', 'high-protein', 'treat'],
    ingredients: '2 tortillas, 100g chicken breast, 30g cheddar, 50g salsa, half bell pepper' },
  { id: 'rice-bowl-tofu', name: 'Teriyaki tofu rice bowl', meal: 'lunch', tags: ['asian', 'bowl'],
    ingredients: '150g tofu, 150g rice, 80g edamame, 1 carrot, 1 tbsp soy sauce, 1 tsp maple syrup, 1 tsp sesame seeds' },

  // ---------- More dinners ----------
  { id: 'fajitas', name: 'Chicken fajitas', meal: 'dinner', tags: ['mexican', 'spicy', 'high-protein', 'post-workout'],
    ingredients: '2 tortillas, 150g chicken breast, 1 bell pepper, half onion, 50g salsa, 30g greek yogurt, 1 tsp olive oil' },
  { id: 'turkey-chili', name: 'Turkey chili with rice', meal: 'dinner', tags: ['spicy', 'filling', 'high-protein', 'make-ahead', 'post-workout'],
    ingredients: '150g ground turkey, 100g kidney beans, 200g chopped tomatoes, half onion, 1 tsp olive oil, 150g rice' },
  { id: 'home-burger', name: 'Homemade beef burger', meal: 'dinner', tags: ['classic', 'treat', 'high-protein'],
    ingredients: '1 burger bun, 120g ground beef, 1 slice cheddar, 20g lettuce, 1 tomato, 1 tbsp ketchup' },
  { id: 'salmon-teriyaki', name: 'Salmon teriyaki with rice & greens', meal: 'dinner', tags: ['asian', 'high-protein', 'post-workout'],
    ingredients: '130g salmon, 150g rice, 150g broccoli, 1 tbsp soy sauce, 1 tsp honey' },
  { id: 'gnocchi-tomato', name: 'Gnocchi with tomato & mozzarella', meal: 'dinner', tags: ['italian', 'quick', 'warm'],
    ingredients: '250g gnocchi, 150g chopped tomatoes, 60g mozzarella, 30g spinach, 1 tsp olive oil' },
  { id: 'halloumi-traybake', name: 'Halloumi & veggie traybake', meal: 'dinner', tags: ['mediterranean', 'warm'],
    ingredients: '80g halloumi, 1 sweet potato, 1 zucchini, 1 bell pepper, 1 tbsp olive oil' },
  { id: 'schnitzel-potatoes', name: 'Schnitzel with potatoes & cucumber salad', meal: 'dinner', tags: ['german', 'classic', 'treat'],
    ingredients: '150g schnitzel, 200g potatoes, 1 cucumber, 1 tbsp salad dressing, half lemon' },
  { id: 'fishfingers-mash', name: 'Fish fingers, mash & peas', meal: 'dinner', tags: ['classic', 'quick', 'kid-favourite'],
    ingredients: '5 fish fingers, 200g mashed potato, 80g peas, 5g butter' },
  { id: 'chicken-curry-rice', name: 'Chicken & spinach curry with rice', meal: 'dinner', tags: ['indian', 'spicy', 'curry', 'high-protein', 'post-workout'],
    ingredients: '150g chicken breast, 100ml coconut milk, 100g spinach, half onion, 100g chopped tomatoes, 150g rice' },
  { id: 'beef-broccoli', name: 'Beef & broccoli stir-fry', meal: 'dinner', tags: ['asian', 'high-protein', 'quick'],
    ingredients: '150g steak, 200g broccoli, 150g rice, 1 tbsp soy sauce, 1 tsp olive oil, 1 clove garlic' },
  { id: 'stuffed-peppers', name: 'Stuffed peppers', meal: 'dinner', tags: ['warm', 'high-protein', 'volume'],
    ingredients: '2 bell peppers, 100g ground beef, 100g rice, 150g chopped tomatoes, 30g mozzarella' },
  { id: 'dinner-omelette', name: 'Ham & cheese omelette with salad', meal: 'dinner', tags: ['quick', 'high-protein', 'low-carb'],
    ingredients: '3 eggs, 30g ham, 20g cheddar, 60g lettuce, 1 tomato, 1 tsp olive oil, 1 slice whole wheat bread' },
  { id: 'lasagne-salad', name: 'Lasagne with side salad', meal: 'dinner', tags: ['italian', 'classic', 'treat'],
    ingredients: '300g lasagna, 60g lettuce, 1 tbsp salad dressing' },
  { id: 'pumpkin-soup', name: 'Pumpkin soup with bread', meal: 'dinner', tags: ['warm', 'soup', 'volume', 'autumn'],
    ingredients: '400g pumpkin, 50ml coconut milk, half onion, 1 tsp olive oil, 2 slices whole wheat bread' },
  { id: 'shrimp-pasta', name: 'Garlic shrimp pasta', meal: 'dinner', tags: ['italian', 'pasta', 'high-protein'],
    ingredients: '180g pasta, 130g shrimp, 100g cherry tomatoes, 2 cloves garlic, 1 tbsp olive oil, 10g parmesan' },
  { id: 'sweet-potato-beans', name: 'Loaded sweet potato with black beans', meal: 'dinner', tags: ['mexican', 'filling', 'warm'],
    ingredients: '1 large sweet potato, 120g black beans, 50g salsa, half avocado, 50g corn' },
  { id: 'tofu-teriyaki', name: 'Tofu teriyaki with noodles', meal: 'dinner', tags: ['asian', 'quick'],
    ingredients: '180g tofu, 180g noodles, 100g broccoli, 1 tbsp soy sauce, 1 tsp maple syrup, 1 tsp sesame seeds' },
  { id: 'currywurst', name: 'Currywurst & fries', meal: 'dinner', tags: ['german', 'treat'],
    ingredients: '1 sausage, 2 tbsp ketchup, 1 serving fries' },
  { id: 'doner', name: 'Döner kebab', meal: 'dinner', tags: ['german', 'treat'],
    ingredients: '1 kebab' },
  { id: 'sushi-dinner', name: 'Sushi & miso-style soup', meal: 'dinner', tags: ['asian', 'treat'],
    ingredients: '12 pieces sushi, 1 bowl soup, 1 tbsp soy sauce' },
  { id: 'eggplant-lentil', name: 'Eggplant & lentil bake', meal: 'dinner', tags: ['mediterranean', 'warm', 'filling'],
    ingredients: '1 eggplant, 200g lentils, 150g chopped tomatoes, 30g feta, 1 tbsp olive oil' },
  { id: 'chicken-wrap-dinner', name: 'Crispy chicken wraps (air fryer)', meal: 'dinner', tags: ['quick', 'high-protein', 'post-workout'],
    ingredients: '2 tortillas, 150g chicken breast, 40g lettuce, 1 tomato, 40g tzatziki' },

  // ---------- More snacks (lots for after sports & evening cravings) ----------
  { id: 'skyr-berries', name: 'Skyr with berries', meal: 'snack', tags: ['high-protein', 'sweet', 'creamy', 'filling', 'post-workout'],
    ingredients: '200g skyr, 100g berries' },
  { id: 'quark-banana', name: 'Quark with banana & honey', meal: 'snack', tags: ['high-protein', 'sweet', 'creamy', 'filling', 'post-workout'],
    ingredients: '250g quark, 1 banana, 1 tsp honey' },
  { id: 'protein-pudding', name: 'Protein pudding', meal: 'snack', tags: ['high-protein', 'sweet', 'creamy', 'post-workout', 'quick'],
    ingredients: '1 protein pudding' },
  { id: 'choc-milk', name: 'Chocolate milk (recovery drink)', meal: 'snack', tags: ['sweet', 'drink', 'post-workout'],
    ingredients: '300ml chocolate milk' },
  { id: 'turkey-rollups', name: 'Turkey & cucumber roll-ups', meal: 'snack', tags: ['high-protein', 'salty', 'volume', 'low-carb'],
    ingredients: '80g turkey, 1 cucumber, 1 tbsp cream cheese' },
  { id: 'tuna-ricecakes', name: 'Tuna rice cakes', meal: 'snack', tags: ['high-protein', 'salty', 'crunchy', 'post-workout'],
    ingredients: '3 rice cakes, half can tuna, 1 tsp mayonnaise, 50g cherry tomatoes' },
  { id: 'egg-crispbread', name: 'Egg on crispbread', meal: 'snack', tags: ['high-protein', 'salty', 'crunchy', 'filling'],
    ingredients: '2 crispbread, 2 eggs' },
  { id: 'jerky-apple', name: 'Beef jerky & an apple', meal: 'snack', tags: ['high-protein', 'salty', 'filling'],
    ingredients: '1 bag beef jerky, 1 apple' },
  { id: 'cottage-tomatoes', name: 'Cottage cheese & cherry tomatoes', meal: 'snack', tags: ['high-protein', 'salty', 'creamy', 'volume'],
    ingredients: '200g cottage cheese, 150g cherry tomatoes' },
  { id: 'cheese-grapes', name: 'Cheese stick & grapes', meal: 'snack', tags: ['sweet', 'quick'],
    ingredients: '1 string cheese, 100g grapes' },
  { id: 'mug-cake', name: 'Protein mug cake (2 min microwave)', meal: 'snack', tags: ['sweet', 'warm', 'high-protein', 'treat'],
    ingredients: '30g oats, 1 egg, half banana, 1 tsp cocoa powder, half scoop protein powder' },
  { id: 'popcorn', name: 'Big bowl of popcorn', meal: 'snack', tags: ['salty', 'crunchy', 'volume', 'movie-night'],
    ingredients: '25g popcorn' },
  { id: 'frozen-grapes', name: 'Frozen grapes', meal: 'snack', tags: ['sweet', 'volume', 'fruit'],
    ingredients: '200g grapes' },
  { id: 'watermelon', name: 'Watermelon wedge', meal: 'snack', tags: ['sweet', 'volume', 'fruit'],
    ingredients: '1 wedge watermelon' },
  { id: 'cucumber-tzatziki', name: 'Cucumber sticks & tzatziki', meal: 'snack', tags: ['salty', 'crunchy', 'volume', 'creamy'],
    ingredients: '1 cucumber, 60g tzatziki' },
  { id: 'veggie-salsa', name: 'Veggie sticks & salsa', meal: 'snack', tags: ['salty', 'crunchy', 'volume'],
    ingredients: '2 carrots, 1 bell pepper, 100g salsa' },
  { id: 'hot-choc', name: 'Hot chocolate', meal: 'snack', tags: ['sweet', 'warm', 'drink', 'evening'],
    ingredients: '250ml hot chocolate' },
  { id: 'tea-chocolate', name: 'Tea & two squares of dark chocolate', meal: 'snack', tags: ['sweet', 'evening', 'treat'],
    ingredients: '1 cup tea, 20g dark chocolate' },
  { id: 'pretzels-cheese', name: 'Pretzels & mini Babybel', meal: 'snack', tags: ['salty', 'crunchy'],
    ingredients: '25g pretzels, 1 mini babybel' },
  { id: 'roasted-chickpeas', name: 'Roasted chickpeas', meal: 'snack', tags: ['salty', 'crunchy', 'filling'],
    ingredients: '30g roasted chickpeas' },
  { id: 'crispbread-cottage', name: 'Crispbread with cottage cheese & tomato', meal: 'snack', tags: ['salty', 'crunchy', 'high-protein'],
    ingredients: '2 crispbread, 100g cottage cheese, 1 tomato' },
  { id: 'nice-cream', name: 'Banana "nice cream"', meal: 'snack', tags: ['sweet', 'creamy', 'treat'],
    ingredients: '1 banana, 50ml milk, 1 tsp cocoa powder' },
  { id: 'rice-pudding', name: 'Rice pudding with cinnamon', meal: 'snack', tags: ['sweet', 'creamy', 'warm'],
    ingredients: '1 pot rice pudding' },
  { id: 'mango-skyr', name: 'Mango skyr', meal: 'snack', tags: ['sweet', 'creamy', 'high-protein', 'post-workout'],
    ingredients: '150g skyr, 100g mango' },
  { id: 'orange-almonds', name: 'Orange & a few almonds', meal: 'snack', tags: ['sweet', 'crunchy', 'quick', 'pre-workout'],
    ingredients: '1 orange, 14g almonds' },
  { id: 'kiwis', name: 'Two kiwis', meal: 'snack', tags: ['sweet', 'fruit', 'quick'],
    ingredients: '2 kiwi' },
  { id: 'salmon-crispbread', name: 'Smoked salmon crispbread', meal: 'snack', tags: ['salty', 'crunchy', 'high-protein'],
    ingredients: '2 crispbread, 40g smoked salmon, 1 tbsp cream cheese' },
  { id: 'protein-bar', name: 'Protein bar', meal: 'snack', tags: ['sweet', 'quick', 'post-workout', 'on-the-go'],
    ingredients: '1 protein bar' },
  { id: 'kefir-drink', name: 'Glass of kefir', meal: 'snack', tags: ['creamy', 'drink', 'quick'],
    ingredients: '1 glass kefir' },
  { id: 'froyo-berries', name: 'Frozen yogurt with berries', meal: 'snack', tags: ['sweet', 'creamy', 'treat'],
    ingredients: '1 scoop frozen yogurt, 100g berries' },
  { id: 'seaweed-ricecake', name: 'Seaweed snacks & rice cakes', meal: 'snack', tags: ['salty', 'crunchy', 'volume', 'asian'],
    ingredients: '1 pack seaweed snack, 2 rice cakes' },
  { id: 'pickles-ham', name: 'Pickles & ham', meal: 'snack', tags: ['salty', 'low-carb', 'volume'],
    ingredients: '3 pickles, 40g ham' },
  { id: 'pb-banana-toast-snack', name: 'Half PB & banana toast', meal: 'snack', tags: ['sweet', 'pre-workout', 'filling'],
    ingredients: '1 slice whole wheat bread, 1 tsp peanut butter, half banana' },
  { id: 'yogurt-granola-snack', name: 'Yogurt with a sprinkle of granola', meal: 'snack', tags: ['sweet', 'creamy', 'crunchy'],
    ingredients: '150g greek yogurt, 20g granola' },
  { id: 'chips-salsa-light', name: 'Small bowl of tortilla chips & salsa', meal: 'snack', tags: ['salty', 'crunchy', 'treat', 'movie-night'],
    ingredients: '25g tortilla chips, 80g salsa' },
];
